### ISSUE TITLE
Xperia 10 aosp 12.0 binaries

### ISSUE THREAD

**Issue by ziomek64** [sonyxperiadev/device-sony-ganges#50]
Hello,
I know it's probably not related to this repo but, where can we expect Aosp 12.0 binaries for Xperia 10?

**Comment by jerpelea** [comment]
they will come soon if all works as expected

**Comment by ziomek64** [comment]
@jerpelea any eta? Like Q1 2022?

**Comment by MarijnS95** [comment]
Without the master branch, where everything for Ganges should still be on the 4.14 kernel, I think you can use Android 11 blobs just fine?

Thanks Treble, HIDL HALs and our inexhaustible effort to keep this maintained.

**Comment by ziomek64** [comment]
@MarijnS95 I know, i just wanted to have android 12 on my phone . I'm not a developer

**Comment by MarijnS95** [comment]
@ziomek64 What I said above means that you can build and run Android 12 on your phone, while using the ODM for Android 11.

**Comment by ziomek64** [comment]
@MarijnS95 oh, that's good news. All functionalities should work fine?
